import Head from 'next/head';
import { Button } from 'primereact/button';
import { Calendar } from 'primereact/calendar';

export default function Home() {
  return (
    <>
      <Head>
        <title>cloudfalre app</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div className="text-5xl font-bold underline">HELLO WORLD</div>
      </div>

      <div className="container">
        <Button label="Show" />
      </div>

      <div className="container">
        <Calendar></Calendar>
      </div>
    </>
  );
}

/**
 * pnpm install husky lint-staged @typescript-eslint/eslint-plugin @typescript-eslint/parser -D
 * pnpm install eslint eslint-config-next eslint-plugin-next eslint-plugin-react eslint-plugin-react-hooks -D
 * pnpm install eslint-plugin-simple-import-sort prettier eslint-config-prettier eslint-plugin-prettier -D
 * pnpm install jest tsconfig-paths ts-jest ts-loader ts-node -D
 */
