import Head from "next/head";
import { Button } from "primereact/button";
import { Calendar } from "primereact/calendar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button label="Show" />
      <Calendar></Calendar>
    </>
  );
}
